apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: backstage-azure-dotnet-template
  title: .Net App with Azure DevOps Actions
  description: Create a DotNet service with Azure DevOps Actions workflows
  tags:
    - recommended
spec:
  owner: peterkavelaars@gmail.com
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - service_name
        - owner
      properties:
        service_name:
          title: Name
          type: string
          description: Unique name of the service.
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this service is for; optional.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          serviceName: ${{ parameters.service_name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:azure
      input:
        allowedHosts: ["dev.azure.com"]
        description: This is ${{ parameters.service_name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
